name: test
on:
  push:
  pull_request:
  workflow_call:
    secrets:
      codecov_token:
        required: true
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        php_version: 8.3
        php_extensions: intl pcntl
    - uses: php-actions/phpunit@v4
      env:
        XDEBUG_MODE: coverage
      with:
        bootstrap: vendor/autoload.php
        configuration: phpunit.xml
        php_version: 8.3
        php_extensions: intl mbstring pcntl xdebug
        args: --coverage-clover ./coverage.xml
    - uses: codecov/codecov-action@v4
      with:
        name: codecov2
        files: ./coverage.xml
        fail_ci_if_error: true
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
